### ISSUE TITLE
Test print Image distorted

### ISSUE THREAD

**Issue by benija123** [DynamixSoftware/PrintingSample#3]
When I print Test Image - I use print() Method in ServiceSample - then the Image is printed in left top corner very small and distorted. How can I customize Image and Printing Area Size? I would like to print Test Image on A4 Paper fullscreen.

**Comment by DynamixSoftware** [comment]
Hi
What print() method do you use? There are several print(). Also, you should check what paper size selected and what bitmap size you are going to print.

**Comment by benija123** [comment]
I Use print() Method in ServiceSample.java File Line 570.
I try to print Bitmap with Width = 2136 and Height = 1424.
I print with Wifi.
Option Papier, current value A4 210x297mm

Bitmap which i want to print:
![screenshot_20171101-165023](https://user-images.githubusercontent.com/6734993/32283840-c8d25bd6-bf25-11e7-8849-b2f72e448d2b.png)

Printed output:
![img_20171101_165518](https://user-images.githubusercontent.com/6734993/32283812-b12d63c2-bf25-11e7-80b3-1e027227b2d7.jpg)
![img_20171101_165523](https://user-images.githubusercontent.com/6734993/32283813-b1455414-bf25-11e7-8903-5ff8fb9257b5.jpg)

**Comment by vll1985** [comment]
Same problem for me...
